### ISSUE TITLE
friendly reminder 

### ISSUE THREAD

**Issue by samlinux** [sschrunner/sschrunner.github.io#1]
https://github.com/sschrunner/sschrunner.github.io/blob/c63d165a87132a499ca1891f06bca353c7555156/index.html#L17

Du solltest die Google Fonts nicht von Google laden, sondern lokal hinterlegen wie Bootstrap, siehe letzte Abmahnwelle !

Lg.

**Comment by sschrunner** [comment]
Vielen Dank für den Hinweis, ein guter Punkt!
Lg
